---
# tasks file for powershell


- name: set gpg key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: add repository
  apt_repository:
    repo: "deb https://packages.microsoft.com/ubuntu/{{ansible_distribution_version}}/prod {{ ansible_distribution_release }} main"
    filename: microsoft.powershell
    state: present
    update_cache: yes

- name: install powershell
  apt:
    name: powershell
    state: latest